### ISSUE TITLE
profile settings

### ISSUE THREAD

**Issue by Valmadson** [Heitor-Tasso/KivyStudioDesigner#2]
Hi, my name is Valmadson, I am studing kivy, and testing KivyStudioDesigner I find a error when to go compile code, message error below. 

[valmadson@arch experimento]$ /home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/bin/python /home/valmadson/Documents/dev/python/kivy/experimento/KivyStudioDesigner/main.py
 Traceback (most recent call last):
   File "/home/valmadson/Documents/dev/python/kivy/experimento/KivyStudioDesigner/main.py", line 217, in <module>
     app.run()
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/app.py", line 955, in run
     runTouchApp()
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/base.py", line 379, in idle
     Clock.tick()
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/clock.py", line 776, in post_idle
     self._process_events()
   File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "/home/valmadson/Documents/dev/python/kivy/experimento/KivyStudioDesigner/designer.py", line 157, in config
     self.prof_settings.load_profiles()
   File "/home/valmadson/Documents/dev/python/kivy/experimento/KivyStudioDesigner/core/profile_settings.py", line 214, in load_profiles
     self.update_panel()     # valmadson
   File "/home/valmadson/Documents/dev/python/kivy/experimento/KivyStudioDesigner/core/profile_settings.py", line 237, in update_panel
     self.add_json_panel(prof_name, self.config_parsers[_file], path_sett)
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/uix/settings.py", line 1044, in add_json_panel
     panel = self.create_json_panel(title, config, filename, data)
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/uix/settings.py", line 1084, in create_json_panel
     instance = cls(panel=panel, **str_settings)
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/uix/settings.py", line 295, in __init__
     self.value = self.panel.get_value(self.section, self.key)
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/uix/settings.py", line 722, in get_value
     return config.get(section, key)
   File "/home/valmadson/.pyenv/versions/3.9.7/envs/kivy39/lib/python3.9/site-packages/kivy/config.py", line 517, in get
     value = PythonConfigParser.get(self, section, option, **kwargs)
   File "/home/valmadson/.pyenv/versions/3.9.7/lib/python3.9/configparser.py", line 781, in get
     d = self._unify_values(section, vars)
   File "/home/valmadson/.pyenv/versions/3.9.7/lib/python3.9/configparser.py", line 1152, in _unify_values
     raise NoSectionError(section) from None
 configparser.NoSectionError: No section: 'profile'
[valmadson@arch experimento]$

**Comment by Heitor-Tasso** [comment]
What operating system are you using?
Did you install KivyStudioDesigner one day?
See this issue and tell me: https://github.com/SrGambiarra/KivyStudioDesigner/issues/1

**Comment by Valmadson** [comment]
SO: Arch Linux
I don't install KivyStudioDesigner. I try : pip install KivyStudioDesigner, 
ERROR: Could not find a version that satisfies the requirement KivyStudioDesigner (from versions: none)
ERROR: No matching distribution found for KivyStudioDesigner

**Comment by Valmadson** [comment]
in requeriments, I already install all in my environment.

**Comment by Heitor-Tasso** [comment]
yes i want to know if you ever used KivyStudioDesigner one day, try removing the folder located in **/home/UserName/.config/programdesigner** and run **main.py** again.
